-- MySQL Script generated by MySQL Workbench
-- Sun Apr 30 15:13:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kzm0099db
-- -----------------------------------------------------
-- Database for Term Project COMP 5120 Spring 2023 Auburn University by Kazybek Mizam

-- -----------------------------------------------------
-- Schema kzm0099db
--
-- Database for Term Project COMP 5120 Spring 2023 Auburn University by Kazybek Mizam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kzm0099db` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `kzm0099db` ;

-- -----------------------------------------------------
-- Table `kzm0099db`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kzm0099db`.`suppliers` (
  `SupplierID` INT NOT NULL,
  `CompanyName` VARCHAR(45) NOT NULL,
  `ContactLastName` VARCHAR(45) NOT NULL,
  `ContactFirstName` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SupplierID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kzm0099db`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kzm0099db`.`subjects` (
  `SubjectID` INT NOT NULL,
  `CategoryName` VARCHAR(45) NULL,
  PRIMARY KEY (`SubjectID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kzm0099db`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kzm0099db`.`books` (
  `BookID` INT NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `UnitPrice` FLOAT NOT NULL,
  `Author` VARCHAR(45) NOT NULL,
  `Quantity` INT NOT NULL,
  `SupplierID` INT NOT NULL,
  `SubjectID` INT NOT NULL,
  PRIMARY KEY (`BookID`),
  INDEX `SupplierID_idx` (`SupplierID` ASC) VISIBLE,
  INDEX `SubjectID_idx` (`SubjectID` ASC) VISIBLE,
  CONSTRAINT `SupplierID`
    FOREIGN KEY (`SupplierID`)
    REFERENCES `kzm0099db`.`suppliers` (`SupplierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SubjectID`
    FOREIGN KEY (`SubjectID`)
    REFERENCES `kzm0099db`.`subjects` (`SubjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kzm0099db`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kzm0099db`.`customers` (
  `CustomerID` INT NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kzm0099db`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kzm0099db`.`employees` (
  `EmployeeID` INT NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EmployeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kzm0099db`.`shippers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kzm0099db`.`shippers` (
  `ShipperID` INT NOT NULL,
  `ShipperName` VARCHAR(45) NULL,
  PRIMARY KEY (`ShipperID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kzm0099db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kzm0099db`.`orders` (
  `OrderID` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  `EmployeeID` INT NOT NULL,
  `OrderDate` DATETIME NOT NULL,
  `ShippedDate` DATETIME NOT NULL,
  `ShipperID` INT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `CustomerID_idx` (`CustomerID` ASC) VISIBLE,
  INDEX `EmployeeID_idx` (`EmployeeID` ASC) VISIBLE,
  INDEX `ShipperID_idx` (`ShipperID` ASC) VISIBLE,
  CONSTRAINT `CustomerID`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `kzm0099db`.`customers` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `EmployeeID`
    FOREIGN KEY (`EmployeeID`)
    REFERENCES `kzm0099db`.`employees` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ShipperID`
    FOREIGN KEY (`ShipperID`)
    REFERENCES `kzm0099db`.`shippers` (`ShipperID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kzm0099db`.`order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kzm0099db`.`order_details` (
  `BookID` INT NOT NULL,
  `OrderID` INT NOT NULL,
  `Quantity` INT NOT NULL,
  PRIMARY KEY (`BookID`, `OrderID`),
  INDEX `OrderID_idx` (`OrderID` ASC) VISIBLE,
  CONSTRAINT `BookID`
    FOREIGN KEY (`BookID`)
    REFERENCES `kzm0099db`.`books` (`BookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `OrderID`
    FOREIGN KEY (`OrderID`)
    REFERENCES `kzm0099db`.`orders` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
