Script started on Mon Nov 16 13:30:29 2020
[1m[7m%[27m[1m[0m                                                                                                                              [0m[27m[24m[Jkazybek@MacBook-Pro-Gulnara P5 % [K[?2004h../project5_Mizam_kzm0099[1m [0m[0m [?2004l
Banner id: 904052049
producer produce item 7
consumer consume item 7
producer produce item 14
consumer consume item 14
producer produce item 21
consumer consume item 21
producer produce item 28
consumer consume item 28
producer produce item 35
consumer consume item 35
producer produce item 42
consumer consume item 42
producer produce item 49
consumer consume item 49
producer produce item 56
consumer consume item 56
producer produce item 63
consumer consume item 63
producer produce item 70
consumer consume item 70
[1m[7m%[27m[1m[0m                                                                                                                              [0m[27m[24m[Jkazybek@MacBook-Pro-Gulnara P5 % [K[?2004heexit[?2004l

Script done on Mon Nov 16 13:30:46 2020
